ALTER TABLE Suppliers
ADD PRIMARY KEY (SupplierID);

ALTER TABLE Products
ADD PRIMARY KEY (ProductID),
ADD FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID),
ADD FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID);

ALTER TABLE Categories
ADD PRIMARY KEY (CategoryID);

ALTER TABLE Customers
ADD PRIMARY KEY (CustomerID);

ALTER TABLE Orders
ADD PRIMARY KEY (OrderID),
ADD FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
ADD FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
ADD FOREIGN KEY (ShipperID) REFERENCES Shippers(ShipperID);

ALTER TABLE OrderDetails
ADD PRIMARY KEY (OrderDetailID),
ADD FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
ADD FOREIGN KEY (ProductID) REFERENCES Products(ProductID);

ALTER TABLE Employees
ADD PRIMARY KEY (EmployeeID);

ALTER TABLE Shippers
ADD PRIMARY KEY (ShipperID);
